KNOWN_SERVICES = {
    "telnetd":     "CRITICAL",
    "utelnetd":    "CRITICAL",
    "rlogind":     "CRITICAL",
    "rshd":        "CRITICAL",
    "rexecd":      "CRITICAL",
    "tftpd":       "CRITICAL",
    "atftpd":      "CRITICAL",

    "ftpd":        "HIGH",
    "vsftpd":      "HIGH",
    "proftpd":     "HIGH",
    "pure-ftpd":   "HIGH",
    "bftpd":       "HIGH",
    "httpd":       "HIGH",
    "uhttpd":      "HIGH",
    "lighttpd":    "HIGH",
    "nginx":       "HIGH",
    "apache":      "HIGH",
    "apache2":     "HIGH",
    "goahead":     "HIGH",
    "boa":         "HIGH",
    "thttpd":      "HIGH",
    "mini_httpd":  "HIGH",
    "minihttpd":   "HIGH",
    "alphapd":     "HIGH",
    "httpd_gargoyle": "HIGH",
    "miniupnpd":   "HIGH",
    "upnpd":       "HIGH",
    "igmpproxy":   "HIGH",
    "snmpd":       "HIGH",
    "net-snmpd":   "HIGH",
    "cwmpd":       "HIGH",
    "tr069":       "HIGH",
    "tr064":       "HIGH",
    "smbd":        "HIGH",
    "nmbd":        "HIGH",
    "afpd":        "HIGH",
    "netatalk":    "HIGH",
    "lpd":         "HIGH",
    "cupsd":       "HIGH",
    "xinetd":      "HIGH",
    "inetd":       "HIGH",

    "sshd":        "MEDIUM",
    "dropbear":    "MEDIUM",
    "dnsmasq":     "MEDIUM",
    "named":       "MEDIUM",
    "bind":        "MEDIUM",
    "unbound":     "MEDIUM",
    "mosquitto":   "MEDIUM",
    "mqttd":       "MEDIUM",
    "emqx":        "MEDIUM",
    "hostapd":     "MEDIUM",
    "wpa_supplicant": "MEDIUM",
    "pppd":        "MEDIUM",
    "pppoe":       "MEDIUM",
    "xl2tpd":      "MEDIUM",
    "openl2tpd":   "MEDIUM",
    "openvpn":     "MEDIUM",
    "ipsec":       "MEDIUM",
    "racoon":      "MEDIUM",
    "zebra":       "MEDIUM",
    "ripd":        "MEDIUM",
    "ospfd":       "MEDIUM",
    "bgpd":        "MEDIUM",
    "dhcpd":       "MEDIUM",
    "dhclient":    "MEDIUM",
    "udhcpd":      "MEDIUM",
    "udhcpc":      "MEDIUM",
    "radvd":       "MEDIUM",
    "avahi-daemon": "MEDIUM",
    "mdnsd":       "MEDIUM",
    "wsdd":        "MEDIUM",
    "lldpd":       "MEDIUM",
    "portmap":     "MEDIUM",
    "rpcbind":     "MEDIUM",
    "nfsd":        "MEDIUM",
    "mountd":      "MEDIUM",
    "statd":       "MEDIUM",
    "ypbind":      "MEDIUM",
    "ypserv":      "MEDIUM",

    "ntpd":        "LOW",
    "chronyd":     "LOW",
    "crond":       "LOW",
    "cron":        "LOW",
    "atd":         "LOW",
    "syslogd":     "LOW",
    "klogd":       "LOW",
    "rsyslogd":    "LOW",
    "syslog-ng":   "LOW",
    "logd":        "LOW",
    "watchdog":    "LOW",
    "monit":       "LOW",
    "collectd":    "LOW",
    "snortd":      "LOW",
    "zabbix_agentd": "LOW",
}

NETWORK_SYMBOLS = {
    "socket", "bind", "listen", "accept", "accept4",
    "connect", "recv", "recvfrom", "recvmsg",
    "send", "sendto", "sendmsg", "select", "poll",
    "epoll_create", "epoll_wait", "getaddrinfo",
}
